name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Astro
        run: |
          if [ -n "${{ secrets.DOMAIN_NAME }}" ]; then
            CUSTOM_DOMAIN=${{ secrets.DOMAIN_NAME }} npm run build
          else
            npm run build
          fi
      
      - name: Create CNAME file if custom domain exists
        run: |
          if [ -n "${{ secrets.DOMAIN_NAME }}" ]; then
            echo "${{ secrets.DOMAIN_NAME }}" > dist/CNAME
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
