import {
  FaFolderOpen,
  FaSearch,
  FaSpotify,
  FaTwitter,
  FaGithub,
  FaLinkedin,
  FaHome,
  FaFile,
  FaRegFile,
  FaChevronDown,
  FaChevronRight,
  FaBars,
  FaAngleDoubleLeft,
  FaAngleDoubleRight,
  FaLightbulb,
  FaRegLightbulb,
  FaSteam,
  FaDiscord,
  FaPalette,
} from 'react-icons/fa';
import { BsToggleOff, BsToggleOn } from 'react-icons/bs';

const ListIcons = {
  Folder: FaFolderOpen,
  Home: FaHome,
  Menu: FaBars,
  Search: FaSearch,
  LightOff: FaLightbulb,
  LightOn: FaRegLightbulb,
  Spotify: FaSpotify,
  Twitter: FaTwitter,
  Github: FaGithub,
  Linkedin: FaLinkedin,
  Steam: FaSteam,
  Discord: FaDiscord,
  FileOutline: FaRegFile,
  File: FaFile,
  ChevronDown: FaChevronDown,
  ChevronRight: FaChevronRight,
  ArrowDoubleLeft: FaAngleDoubleLeft,
  ArrowDoubleRight: FaAngleDoubleRight,
  ToggleOn: BsToggleOn,
  ToggleOff: BsToggleOff,
  Palette: FaPalette,
};

export default ListIcons;
